### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by Veriiix** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#1]
This message always appears after ending a prompt

**Comment by MichielvanBeers** [comment]
Hi @Veriiix,

Thanks for the feedback. Some questions to help me debug: 

- Do you get any additional information in the subtitle (under the message 'An error occurred') about the error? 
- Have you validated that the API key you are using is working correctly?

Thanks!

**Comment by MichielvanBeers** [comment]
Also, which model have you selected in your settings?

**Comment by MichielvanBeers** [comment]
Closing this issue due to no new responses. Please reopen when you have any additional question.
