### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by bigbadblo** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#10]
Successfully was able to invoke 'ai' without an error on the save-prompts branch, but all responses error out with the following KeyError. Is the ability to report errors from the plugin directly new? It made this report much easier if so -- thank you!

> <details open><summary>Trace Log</summary>
> <p>
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\lib\flox\launcher.py", line 44, in run
>     results = request_method(*request_parameters) or self._results
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\lib\flox\__init__.py", line 132, in _query
>     self.query(query)
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 52, in query
>     prompt, prompt_keyword, system_message = self.split_prompt(query)
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 184, in split_prompt
>     system_message = row["System Message"]
> KeyError: 'System Message'
> 
> ```
> </p>
> </details>

**Comment by MichielvanBeers** [comment]
Great, some progress :) Can you confirm that you have the system_messages.csv file in the plugin folder with at least one key word and system message?

The error logging feature is from someone else, but glad to hear it works well :)

**Comment by MichielvanBeers** [comment]
Some progress, that is good :). Can you share the content of your `system_messages.csv` file?

The ability to report errors directly is from the [Flox library](https://github.com/Garulf/Flox) by Garul, so all credits there :)

**Comment by MichielvanBeers** [comment]
Also, could you set your Logging Level setting to 'Debug' and share the content of `plugin.log` here? Please note that it be default also prints your OpenAI key, so please remove that before posting. Thanks!

**Comment by MichielvanBeers** [comment]
Great, happy to hear it is working!

I also see what might be going wrong: when saving the csv file, I think Excel uses by default a comma ',' delimiter. Since I've set the delimiter to a semi colon ';' (because the default setences contain commas), when saving the csv, Excel assumes the commas determine a new column.

I'll do some research if I can do a check if all the content can be read correctly, before loading the rest of the plugin.

Can I for now close this issue and create a new version? Or are you missing any functionalities?

**Comment by bigbadblo** [comment]
No, I think this is resolved and closed! Success, and thank you very much! :)
