### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by almacd3571** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#17]
Hello,

Not sure if this is due to chatGPT or something on your end, but I see this message no matter what now (uninstalled plugin, uninstalled flow, downloaded flow again, downloaded plugin again, rebooted)

![image](https://user-images.githubusercontent.com/129991222/230174356-21b08e3b-b5da-45e1-a0b7-9d48f19a547c.png)

**Comment by almacd3571** [comment]
Also I have grabbed new API keys daily to see if that might have been the issue, still didnt work.

**Comment by MichielvanBeers** [comment]
Hi @almacd3571, looking at the error, it looks like something is off with your provided payment options. Could you go [here](https://platform.openai.com/account/billing/overview) to see if you can resolve the issue?

**Comment by AnaelBonnafous** [comment]
I have the same issue with my free trial account, does it require upgrading to a paid plan ?

**Comment by almacd3571** [comment]
@MichielvanBeers I think its a bug within openAI as I have the free account, AND they wont allow me to upgrade (I guess they have closed the upgrades for now) I was wondering if anyone else was seeing this error. I wonder if @AnaelBonnafous  is correct and we need paid accounts?

**Comment by almacd3571** [comment]
I have purchased the paid version of CHATgpt, now unable to use either 3.5 or gpt4 (even though I have access on the site itself) 
![image](https://user-images.githubusercontent.com/129991222/235233712-2e1e6bba-a8b4-41e7-b15f-d09bc7e2fe93.png)

**Comment by MichielvanBeers** [comment]
@almacd3571, ChatGPT unfortunately doesn't give you access to the gpt-4 API. You can join the waitlist for access to the API [here](https://openai.com/waitlist/gpt-4-api )

**Comment by MichielvanBeers** [comment]
Marking this issue as stale as there hasn't been any activity on this in a while. Please reopen if you need additional help. Thanks for your contribution!
