### ISSUE TITLE
API Key not saving

### ISSUE THREAD

**Issue by TheStxfan** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#21]
I got an api key, but when I paste in the API Key field and type ai in the flow launcher field suddenly it says Unable to load the API key and the key disappears form the api field in flow launcher plugins settings.

**Comment by MichielvanBeers** [comment]
Hi @TheStxfan, did you run the Save Settings command  after setting the API key? Just launch Flow Launcher, type Save Settings and tap enter.

**Comment by TheStxfan** [comment]
Thank you so much @MichielvanBeers , typing Save Settings worked, but now there is another issue:

![image](https://user-images.githubusercontent.com/109021123/230797869-105907a0-d04c-4ac8-9a58-3624cc03eab4.png)

How can I fix it?

**Comment by MichielvanBeers** [comment]
No problem! This error seems to be when you haven't connected any payment method yet to your OpenAI account. If you go [here](https://platform.openai.com/account/billing/overview) you should be able to resolve the issue. Good luck!

**Comment by TheStxfan** [comment]
> No problem! This error seems to be when you haven't connected any payment method yet to your OpenAI account. If you go [here](https://platform.openai.com/account/billing/overview) you should be able to resolve the issue. Good luck!

Thank you for the help but I couldn't find a way to connect a payment method without paying. Do I have to pay? If not, how can I connect it?

**Comment by MichielvanBeers** [comment]
When using the API instead of the chat.openai.com webpage, you indeed have to pay for the number of Tokens that you use. When using the gpt-3.5-turbo model, this is significantly cheaper than ChatGPT Plus though. You can add a payment method here: https://platform.openai.com/account/billing/payment-methods.

**Comment by TheStxfan** [comment]
> When using the API instead of the chat.openai.com webpage, you indeed have to pay for the number of Tokens that you use. When using the gpt-3.5-turbo model, this is significantly cheaper than ChatGPT Plus though. You can add a payment method here: https://platform.openai.com/account/billing/payment-methods.

Ok, thank you so much again. I would prefer not to pay. But that's not your problem of course.
Thank you!
