### ISSUE TITLE
Precise if ChatGPT plugin for FL can be used for ChatGPT users with no paying subscription

### ISSUE THREAD

**Issue by oeloo** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#26]
In the doc of this ChatGPT plugin, there is no mention (or reference) to the fact that you need to have a paying subscription to ChatGPT. Can you please add this ?
For information, I have a non free ChatGPT subscription and when I try this FL plugin for ChatGPT I have the following error message:
`An error occurred 
You exceeded your current quota, please check your plan and billing detail...`

It was my 1st ChatGPT search, so no quota was exceeded. Unless it is only for ChatGPT paid users. Sadly there is no mention about this the ChatGPT plugin for Flow Launcher support page.

**Comment by MichielvanBeers** [comment]
Hi @oeloo, thanks for the feedback! I've been a paying subscriber on OpenAI from the start, so I wasn't aware of this. I'll make sure to update the documentation
