### ISSUE TITLE
Logging chat records to .txt file?

### ISSUE THREAD

**Issue by bigbadblo** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#4]
Given this plugin's current functionality, I am curious if it would be possible to expand the option of opening ChatGPT's responses in a .txt file to also save these responses as an iterative log of both user prompts and GPT's responses (saved locally)?

For example, I've just asked ChatGPT the following: 
> ai how can I write code that will generate a .txt file with a saved record of our conversation together? ||

ChatGPT's response: 
> To generate a .txt file with a saved record of our conversation, you can use the following Python code:
> 
> ```
> # Open a new file in write mode
> with open('conversation.txt', 'w') as file:
>    # Write the conversation to the file
>    file.write('Here is a record of our conversation:\n')
>    for message in messages: # messages is a list of our conversation
>       file.write(message + '\n')
> print('Conversation saved in conversation.txt')
> ```
> 
> In this code, we first open a new file called "conversation.txt" in write mode. Using the `with` statement ensures that the file is closed properly after it's done being written to. 
> 
> Inside the `with` block, we write a header to the file indicating that it's a record of our conversation. Then, we iterate over each message in the `messages` list (which would contain all the messages in our conversation) and write each one to a new line in the file.
> 
> Finally, we print a message indicating that the conversation has been saved in the file.
> 
> Make sure to replace the `messages` list with the actual list of messages that you want to save.

I don't have the understanding to implement this as a request, but wanted to leave this as a topic for consideration. Storing a local record of both prompts and the responses would be especially helpful when GPT is overloaded, or chat history is not saved displaying correctly on OpenAI's website. 

Thanks for all of your work on this so far! Cheers!

**Comment by bigbadblo** [comment]
Both are good questions. My initial thinking on these two points are linked: first, I've been thinking that logging every prompt might become excessive, especially when just invoking the **normal** keyword when bringing up FlowLauncher. However, for some this might be helpful -- could there be a selectable option or system setting in the plugin to elect to store all prompts? If so, perhaps the .txt file size becomes an eventual issue?

Or... secondarily and perhaps more interestingly, I wonder if the option to store prompts and answers in a .txt file might work best for any **custom** keywords that are created? I.e., anything that is invoked with normal, short or long keywords isn't stored... but if you create a customized keyword prompt that differs, to then have the option to save and store those customized prompts. In doing it this way, if you are customizing and engineering your own prompts, your ongoing chat history (which is possibly more valuable to reuse and ensure continuity and chat history) is thus saved?

**Comment by MichielvanBeers** [comment]
Ah, I see what you mean now. Simply storing the prompts and the answers is definitely possible! I have already some plans this weekend, but I'll put it on my to-do list :).

I was thinking you proposed having the ability to continue the conversation based on your previous inputs. For example, as described in the section Steerability: Socratic tutor on [this page ](https://openai.com/research/gpt-4 )of OpenAI. If you have some ideas about how that might look, I'm willing to give that a throw as well.

**Comment by MichielvanBeers** [comment]
@bigbadblo I've created a new branch with the ability to save data to a text file under [this branch](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/tree/ability-to-save-prompts-and-answers). Do you have the time to check if this matches your expectations? You can load this version of the plugin by going to the link, downloading it as a zip file and manually adding it to your plugins folder. Looking forward to your feedback!

**Comment by bigbadblo** [comment]
Just gave it a spin and I keep getting the following crash/error when invoking:

> Flow Launcher version: 1.14.0
> OS Version: Microsoft Windows NT 10.0.19045.0
> IntPtr Length: 8
> x64: True
> 
> Python Path: C:\Users\brian\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
> Node Path: 
> Date: 03/27/2023 06:47:01
> Exception:
> ChatGPT Exception: 
> Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
> Author: Flow Launcher
> Version: 1.1.0
> Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\main.py", line 11, in <module>
>     from plugin.main import ChatGPT
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 14, in <module>
>     class ChatGPT(Flox):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 90, in ChatGPT
>     ) -> tuple[str, datetime, datetime]:
> TypeError: 'type' object is not subscriptable
> 
>  ---> System.IO.InvalidDataException: Traceback (most recent call last):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\main.py", line 11, in <module>
>     from plugin.main import ChatGPT
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 14, in <module>
>     class ChatGPT(Flox):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 90, in ChatGPT
>     ) -> tuple[str, datetime, datetime]:
> TypeError: 'type' object is not subscriptable
> 
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
>    at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
> --- End of stack trace from previous location ---
>    at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
>    --- End of inner exception stack trace ---
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
>    at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
> --- End of stack trace from previous location ---
>    at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Oops, sloppy of me, I needed to make the change in two places. I also found another small bug, that should be resolved now. Hopefully everything works like this!

**Comment by bigbadblo** [comment]
> Flow Launcher version: 1.14.0
> OS Version: Microsoft Windows NT 10.0.19045.0
> IntPtr Length: 8
> x64: True
> 
> Python Path: C:\Users\brian\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
> Node Path: 
> Date: 03/27/2023 10:55:32
> Exception:
> ChatGPT Exception: 
> Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
> Author: Flow Launcher
> Version: 1.1.0
> Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\main.py", line 11, in <module>
>     from plugin.main import ChatGPT
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 15, in <module>
>     class ChatGPT(Flox):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 210, in ChatGPT
>     def open_in_editor(self, filename: str | None, answer: str | None) -> None:
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
> 
>  ---> System.IO.InvalidDataException: Traceback (most recent call last):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\main.py", line 11, in <module>
>     from plugin.main import ChatGPT
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 15, in <module>
>     class ChatGPT(Flox):
>   File "C:\Users\brian\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.ChatGPT-ability-to-save-prompts-and-answers\plugin\main.py", line 210, in ChatGPT
>     def open_in_editor(self, filename: str | None, answer: str | None) -> None:
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
> 
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
>    at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
> --- End of stack trace from previous location ---
>    at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
>    --- End of inner exception stack trace ---
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
>    at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 829
> --- End of stack trace from previous location ---
>    at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 

Let me know if there's anything else you'd like me to test as well -- happy to help. :)

**Comment by MichielvanBeers** [comment]
Okay, note to future self: first check which Python version is being bundled with Flowlauncher and then do updates to your code :)

I double-checked it and should have resolved all compatibility issues. Thanks for all the tests. Hope that this was the last fix!
