### ISSUE TITLE
API Key dissappearing

### ISSUE THREAD

**Issue by Verlaire** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#40]
Hi,

The plugin loads fine, then I paste a fresh key (just generated for this app) and all goes well. I close the settings, and invoking the AI command, I get:

![image](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/assets/30931220/4a11a71a-9021-4aeb-97aa-7896a2eeec4c)

What's going on? I am doing something wrong? - BTW I have a paid OpenAI account already.

Thanks in advance!

**Comment by Verlaire** [comment]
Forgot to add, reopening the Settings again, shows an empty field in the API Key field.

**Comment by MichielvanBeers** [comment]
Hi @Verlaire, after entering the key, did you run the 'Save Settings' command? Otherwise the settings are not persisted

**Comment by ntp777** [comment]
> Hi @Verlaire, after entering the key, did you run the 'Save Settings' command? Otherwise the settings are not persisted

Sorry to be super dense, but where is the 'save settings' command located? I've looked and looked :)

**Comment by MichielvanBeers** [comment]
Haha, no worries, you should open Flow Launcher (the part where you can type commands, not the settings) and then type 'Save Settings'. An option the menu should pop up. Hit enter on that menu item and your settings should be saved :). Good luck!

**Comment by bigsk1** [comment]
must have system commands activated, great plugin thanks.
