### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by karthikvijay5227** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#42]
ChatGPT plugin issue in Flow Launcher.When providing the api key,it is getting disappeared and showing error unable to load the api key.

**Comment by MichielvanBeers** [comment]
Hi @karthikvijay5227,

Have your in the 'Save Settings' command in the launcher after entering the key? That should be done to persist any changes, thus as entering the key.

**Comment by faysal253** [comment]
Thanks @MichielvanBeers . I has a problme with this
