### ISSUE TITLE
[FEATURE REQUEST] Show the whole response on right side of Flow launcher

### ISSUE THREAD

**Issue by mlazzarotto** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#44]
I find that most of the time ChatGPT response is longer that the space available on Flow launcher, despite setting 'short' in the settings, and I find myself to open the text file to see the whole response:
![image](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/assets/8932945/1fc7f8a2-56e3-438a-85b6-241dcd376867)
Would be possible to show the full answer on the right side (where it says: "Copy to clipboard")?

**Comment by MichielvanBeers** [comment]
Hi @mlazzarotto, that is a great idea indeed! I've looked through the Flow Launcher documentation, but I didn't find a way to increase the height of the preview in the bottom right corner. Might be a good idea to do a feature request with [Flow Launcher itself](https://github.com/Flow-Launcher/Flow.Launcher), to support this:

**Comment by MichielvanBeers** [comment]
Hi @mlazzarotto, that is great, happy you found a way! I'll put it on the list for the update that I will be doing to make this configurable
