### ISSUE TITLE
SSL Error - SSL Module Not Available

### ISSUE THREAD

**Issue by gooseyman** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#5]
![image](https://user-images.githubusercontent.com/46906376/227311963-262e1802-8699-4192-91aa-e2beb14896a3.png)

Hey Michiel - I'm having an issue with the SSL package. My API token is correct input. Flow settings are pointed at the GPT3 endpoint.

**Comment by MichielvanBeers** [comment]
Hi @gooseyman,

Thanks for the feedback! Going from the error log, it looks like an error with Python or one of its dependencies. Could you confirm that you have set the Python Path under Settings > General? And if so, which Python version does it show in your file path? Should look something like this (on Windows):
Python Path: 
`C:\Users\[username]\AppData\Local\Programs\Python\Python310\pythonw.exe`

**Comment by J-Lich** [comment]
Hi Michiel,
I am having the same issue. I have tried the following:

- Confirmed running latest Flow Launcher (1.14.0)
- Confirmed running latest Plugin (1.1.2)
- Tried embedded python (3.8.9) and standalon (3.10.11) - as indicated above
- Tried HTTP proxy to eliminate any network issues
- Confirmed API key
- Tried 3.5 and 4

However I am still getting the same error. Any advice?

**Comment by MichielvanBeers** [comment]
Hi @J-Lich,

Hmm, that is strange. Are you able to use ChatGPT in the Playground via this link: https://platform.openai.com/playground?mode=chat ?

**Comment by J-Lich** [comment]
Playground works just fine 🤷‍♂️
Any other suggestions?

![image](https://user-images.githubusercontent.com/13187191/231364887-7ce69d48-9258-4028-967a-32bf559ca56c.png)

![image](https://user-images.githubusercontent.com/13187191/231364927-6b7ecdb1-338b-4b15-9d02-39f7d4ee1397.png)

**Comment by MichielvanBeers** [comment]
Could you try (as a temporary workaround to debug the issue), try the following:

1. Open the plugin settings
2. Click the folder icon to open the plugin folder
3. Go to /plugin/main.py
4. On line 123 add `verify=False`, The complete line should then be `"POST", url, headers=headers, data=data, proxies=PROXIES, verify=False`
5. Save
6. Try again

This temporarily skips the check for the SSL certificate, so it definitely shouldn't stay there, but it can help us pinpoint the exact issue. Good luck!
