### ISSUE TITLE
[FEATURE REQUEST] Display Responses on Multiple Lines

### ISSUE THREAD

**Issue by ibrahim-kabir** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#53]
I really love the plugin and the feature of adding prompts. However, I find it inconvenient that the response is displayed on a single line. It would be great if the responses could be displayed on multiple lines to improve readability. Currently, I have to either copy the response or open a text editor to see what the engine replied. It would greatly enhance the user experience if the responses could be readable before selecting one of the option. Thank you!

**Comment by MichielvanBeers** [comment]
Hi @ibrahim-kabir, I definitely like your suggestion, however this is something that I cannot control unfortunately. You could reach out to the creators of FlowLauncher to see if they are interested in adding such a feature. 

Alternatively, you can go to the settings to turn on the file preview. That should give you a tiny bit more text.

Good luck!
