### ISSUE TITLE
How to Add an API Key in the Plugin?

### ISSUE THREAD

**Issue by ajayts07** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#54]
Hello Team,

Can you please help me how can I add my ChatGPT API Key in the plugin according to what you mentioned I can not see any options where I can place the API Key. 

Please assist.

**Comment by MichielvanBeers** [comment]
Hi @ajayts07, did you try the steps described in the documentation here: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT?tab=readme-ov-file#installation? You can add it under the settings menu in Flow Launcher.

**Comment by MichielvanBeers** [comment]
Closing this issue since it has been marked as stall. Please create a new issue if this is still a problem. Thank you for your contribution!
