### ISSUE TITLE
New GPT models

### ISSUE THREAD

**Issue by DRYN07** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#55]
Should I see new models like GPT-4o? Or is that the -0613?

![image](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/assets/29770761/f1098e19-f5c6-4cd6-b9aa-3f233aefab70)

**Comment by mlazzarotto** [comment]
The list of models is hard coded inside the plugin configuration. Therefore, unless you want to wait for an update from the developer, you can manually add GPT 4o in your computer.
To do so, go to `%APPDATA%\FlowLauncher\Plugins\ChatGPT-1.2.0\`, open **SettingsTemplate.yaml** and add  `- gpt-4o`.

``` yaml
      options:
        - gpt-3.5-turbo
        - gpt-4
        - gpt-4-0125-preview
        - gpt-4-turbo-preview
        - gpt-4-1106-preview
        - gpt-4-0613
        - gpt-4o
```

Finally, save Flow Launcher settings and restart it.
