### ISSUE TITLE
Feature request: Ability to change API endpoint.

### ISSUE THREAD

**Issue by notraiday** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#64]
I have my own Open AI-compatible panel with API. I'd like to use it instead of official one. 
Proxy support would be great too.

**Comment by bigsby-exe** [comment]
Have a look at #57, while it's not as easy as changing a config it seems it would be possible to do what you want.

**Comment by MichielvanBeers** [comment]
@notraiday let me know if the workaround in #57, then I can maybe incorporate it as a setting.

Regarding the Proxy: you should be able to set the Proxy in the Flowlauncher settings. The plugin should pick those up automatically.

**Comment by MichielvanBeers** [comment]
Thanks to @Peteryhs (#66) this feature will be available in version 1.3.0.
