### ISSUE TITLE
Chatgpt "exceeded quota"

### ISSUE THREAD

**Issue by Cradyy12** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#65]
Hi, I hope this is the right place to ask as it's my first time using Github. 

I was hoping to use the Chatgpt plugin, and have pasted the API key in the settings part of the plugin. However when I try to prompt anything it returns something along the lines of "You exceeded your current quota..." From what I know isn't the 4o-mini model free? 

I was previously using Fluent Search and I was able to use chatgpt without signing in, how can I replicate this on Flow Launcher? Thank you for your help. 

[](url)
![error](https://github.com/user-attachments/assets/bf0c11c9-6ba8-4d94-b1d6-2e3b1cfbb957)

**Comment by MichielvanBeers** [comment]
Hi @Cradyy12,

In order to use the OpenAI APIs you need to add some credits to your account. You can add them [here ](https://platform.openai.com/settings/organization/billing/overview) in your profile. Good luck!
